.TH "CmdLine" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdLine \- Singleton encargado de mantener la informacion pasada por la linea de comandos\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Singleton encargado de mantener la informacion pasada por la linea de comandos\&. 

Aqui ponemos mas cosas 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
