.TH "daatetime" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
daatetime \- Fechas y horas
.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
