.TH "Date" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Date \- Clase \fBDate\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Clase \fBDate\fP\&. 

Abstrae el concepto de fecha
.PP
Metodos**
.PP
int getMonth ();
.PP
int getDay ();
.PP
sstring toString (const char *fmt = '%F');
.PP
const char * toChar (const char *fmt = '%F'); 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
