.TH "exceptions" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions \- Exceptions
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBToolsException\fP"
.br
.RI "Base clase for exception into the library\&. "
.ti -1c
.RI "class \fBToolsValueException\fP"
.br
.RI "Exception when data not fit the range of values\&. "
.ti -1c
.RI "class \fBToolsCastException\fP"
.br
.RI "Exception when it is not possible construct the object using data passed to constructor\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Exceptions throwed
.PP
Main target of these tools is check when some string can be casted to another type\&. In exmple, trying to construct a date from '2020/02/31' must thrown an exception because february has not 31 days 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
