.TH "Integer" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Integer \- \fBInteger\fP numbers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBInteger\fP (\fBsstring\fP value)"
.br
.RI "Construct a \fBInteger\fP number from an string\&. "
.ti -1c
.RI "\fBInteger\fP (const char *value)"
.br
.RI "Construct a \fBInteger\fP number from an char array\&. "
.ti -1c
.RI "\fBInteger\fP (short value)"
.br
.RI "Construct a \fBInteger\fP number from a short number\&. "
.ti -1c
.RI "\fBInteger\fP (int value)"
.br
.RI "Construct a \fBInteger\fP number from a int number\&. "
.ti -1c
.RI "\fBInteger\fP (long value)"
.br
.RI "Construct a \fBInteger\fP number from a long number\&. "
.ti -1c
.RI "\fBInteger\fP (long long value)"
.br
.RI "Construct a \fBInteger\fP number from a long long number\&. "
.ti -1c
.RI "bool \fBisShort\fP ()"
.br
.ti -1c
.RI "bool \fBisInt\fP ()"
.br
.ti -1c
.RI "bool \fBisLong\fP ()"
.br
.ti -1c
.RI "bool \fBisLongLong\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
\fBInteger\fP numbers\&. 

A \fBInteger\fP number is an integer, not decimal, number, positive or negative 
.PP
Definición en la línea \fB9\fP del archivo \fBinteger\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBInteger\fP (\fBsstring\fP value)\fC [inline]\fP"

.PP
Construct a \fBInteger\fP number from an string\&. 
.PP
Definición en la línea \fB12\fP del archivo \fBinteger\&.hpp\fP\&.
.SS "\fBInteger\fP (const char * value)"

.PP
Construct a \fBInteger\fP number from an char array\&. 
.PP
Definición en la línea \fB18\fP del archivo \fBinteger\&.cpp\fP\&.
.SS "\fBInteger\fP (short value)"

.PP
Construct a \fBInteger\fP number from a short number\&. 
.PP
Definición en la línea \fB14\fP del archivo \fBinteger\&.cpp\fP\&.
.SS "\fBInteger\fP (int value)"

.PP
Construct a \fBInteger\fP number from a int number\&. 
.PP
Definición en la línea \fB15\fP del archivo \fBinteger\&.cpp\fP\&.
.SS "\fBInteger\fP (long value)"

.PP
Construct a \fBInteger\fP number from a long number\&. 
.PP
Definición en la línea \fB16\fP del archivo \fBinteger\&.cpp\fP\&.
.SS "\fBInteger\fP (long long value)"

.PP
Construct a \fBInteger\fP number from a long long number\&. 
.PP
Definición en la línea \fB17\fP del archivo \fBinteger\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "bool isInt ()\fC [inline]\fP"

.PP
Definición en la línea \fB19\fP del archivo \fBinteger\&.hpp\fP\&.
.SS "isLong ()\fC [inline]\fP"

.PP
\fBDevuelve\fP
.RS 4
TRUE if \fBInteger\fP fit in a primitive long type 
.RE
.PP

.PP
Definición en la línea \fB20\fP del archivo \fBinteger\&.hpp\fP\&.
.SS "isLongLong ()\fC [inline]\fP"

.PP
\fBDevuelve\fP
.RS 4
TRUE if \fBInteger\fP fit in a primitive long long type 
.RE
.PP

.PP
Definición en la línea \fB21\fP del archivo \fBinteger\&.hpp\fP\&.
.SS "isShort ()\fC [inline]\fP"

.PP
\fBDevuelve\fP
.RS 4
TRUE if \fBInteger\fP fit in a primitive short type 
.RE
.PP

.PP
Definición en la línea \fB18\fP del archivo \fBinteger\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
