.TH "ToolsValueException" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolsValueException \- Exception when data not fit the range of values\&.  

.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBToolsException\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBToolsValueException\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Exception when data not fit the range of values\&. 
.PP
Definición en la línea \fB18\fP del archivo \fBexceptions\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBToolsValueException\fP (const char * fmt,  \&.\&.\&.)"

.PP
Definición en la línea \fB39\fP del archivo \fBexceptions\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
