.TH "ToolsCastException" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolsCastException
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBToolsException\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBToolsCastException\fP (const char *fmt,\&.\&.\&.)"
.br
.RI "Constructor for the exception\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB24\fP del archivo \fBexceptions\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBToolsCastException\fP (const char * fmt,  \&.\&.\&.)"

.PP
Constructor for the exception\&. 
.PP
\fBParámetros\fP
.RS 4
\fIfmt\fP Pattern to mount the message used in what 
.br
\fI\&.\&.\&.\fP values for pattern 
.RE
.PP

.PP
Definición en la línea \fB45\fP del archivo \fBexceptions\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
