.TH "Time" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Time
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBTime\fP (const \fBTime\fP &src)"
.br
.ti -1c
.RI "\fBTime\fP (string str)"
.br
.ti -1c
.RI "\fBTime\fP (const char *str)"
.br
.ti -1c
.RI "struct tm * \fBgetTM\fP ()"
.br
.ti -1c
.RI "\fBsstring\fP \fBtoString\fP (const char *fmt='%X')"
.br
.ti -1c
.RI "const char * \fBtoChar\fP (const char *fmt='%X')"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB14\fP del archivo \fBtime\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBTime\fP (const \fBTime\fP & src)"

.PP
Definición en la línea \fB16\fP del archivo \fBtime\&.cpp\fP\&.
.SS "\fBTime\fP (string str)"

.PP
Definición en la línea \fB14\fP del archivo \fBtime\&.cpp\fP\&.
.SS "\fBTime\fP (const char * str)"

.PP
Definición en la línea \fB15\fP del archivo \fBtime\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "struct tm * getTM ()"

.PP
Definición en la línea \fB18\fP del archivo \fBtime\&.cpp\fP\&.
.SS "const char * toChar (const char * fmt = \fC'%X'\fP)"

.PP
Definición en la línea \fB20\fP del archivo \fBtime\&.cpp\fP\&.
.SS "\fBsstring\fP toString (const char * fmt = \fC'%X'\fP)"

.PP
Definición en la línea \fB19\fP del archivo \fBtime\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
