.TH "DateImpl" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateImpl
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBDateImpl\fP (\fBsstring\fP str, int fmt)"
.br
.ti -1c
.RI "int \fBgetYear\fP ()"
.br
.ti -1c
.RI "int \fBgetMonth\fP ()"
.br
.ti -1c
.RI "int \fBgetDay\fP ()"
.br
.ti -1c
.RI "struct tm * \fBgetTM\fP ()"
.br
.ti -1c
.RI "\fBsstring\fP \fBtoString\fP (const char *fmt)"
.br
.ti -1c
.RI "const char * \fBtoChar\fP (const char *fmt)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB17\fP del archivo \fBdate\&.cpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBDateImpl\fP (\fBsstring\fP str, int fmt)\fC [inline]\fP"

.PP
Definición en la línea \fB19\fP del archivo \fBdate\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "int getDay ()\fC [inline]\fP"

.PP
Definición en la línea \fB25\fP del archivo \fBdate\&.cpp\fP\&.
.SS "int getMonth ()\fC [inline]\fP"

.PP
Definición en la línea \fB24\fP del archivo \fBdate\&.cpp\fP\&.
.SS "struct tm * getTM ()\fC [inline]\fP"

.PP
Definición en la línea \fB26\fP del archivo \fBdate\&.cpp\fP\&.
.SS "int getYear ()\fC [inline]\fP"

.PP
Definición en la línea \fB23\fP del archivo \fBdate\&.cpp\fP\&.
.SS "const char * toChar (const char * fmt)\fC [inline]\fP"

.PP
Definición en la línea \fB28\fP del archivo \fBdate\&.cpp\fP\&.
.SS "\fBsstring\fP toString (const char * fmt)\fC [inline]\fP"

.PP
Definición en la línea \fB27\fP del archivo \fBdate\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
