.TH "DateTime" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateTime
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBTimestamp\fP\&.
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBDateTimeImpl\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBDateTime\fP (\fBsstring\fP str)"
.br
.ti -1c
.RI "\fBDateTime\fP (const char *str)"
.br
.ti -1c
.RI "\fBsstring\fP \fBtoString\fP ()"
.br
.ti -1c
.RI "const char * \fBtoChar\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB7\fP del archivo \fBdatetime\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBDateTime\fP ()"

.PP
Definición en la línea \fB40\fP del archivo \fBdatetime\&.cpp\fP\&.
.SS "\fBDateTime\fP (\fBsstring\fP str)"

.PP
Definición en la línea \fB41\fP del archivo \fBdatetime\&.cpp\fP\&.
.SS "\fBDateTime\fP (const char * str)"

.PP
Definición en la línea \fB42\fP del archivo \fBdatetime\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "const char * toChar ()"

.PP
Definición en la línea \fB44\fP del archivo \fBdatetime\&.cpp\fP\&.
.SS "\fBsstring\fP toString ()"

.PP
Definición en la línea \fB43\fP del archivo \fBdatetime\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
