.TH "Path" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Path
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBPath\fP (string value)"
.br
.ti -1c
.RI "\fBPath\fP (const char *value)"
.br
.ti -1c
.RI "bool \fBisDir\fP ()"
.br
.ti -1c
.RI "bool \fBisFile\fP ()"
.br
.ti -1c
.RI "bool \fBexists\fP ()"
.br
.ti -1c
.RI "string \fBgetDrive\fP ()"
.br
.ti -1c
.RI "string \fBgetDir\fP ()"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "string \fBgetExt\fP ()"
.br
.ti -1c
.RI "string \fBgetPath\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB9\fP del archivo \fBpath\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBPath\fP (string value)"

.PP
Definición en la línea \fB9\fP del archivo \fBpath\&.cpp\fP\&.
.SS "\fBPath\fP (const char * value)"

.PP
Definición en la línea \fB10\fP del archivo \fBpath\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "bool exists ()"

.PP
Definición en la línea \fB13\fP del archivo \fBpath\&.cpp\fP\&.
.SS "string getDir ()"

.PP
Definición en la línea \fB15\fP del archivo \fBpath\&.cpp\fP\&.
.SS "string getDrive ()"

.PP
Definición en la línea \fB14\fP del archivo \fBpath\&.cpp\fP\&.
.SS "string getExt ()"

.PP
Definición en la línea \fB17\fP del archivo \fBpath\&.cpp\fP\&.
.SS "string getName ()"

.PP
Definición en la línea \fB16\fP del archivo \fBpath\&.cpp\fP\&.
.SS "string getPath ()"

.PP
Definición en la línea \fB18\fP del archivo \fBpath\&.cpp\fP\&.
.SS "bool isDir ()"

.PP
Definición en la línea \fB11\fP del archivo \fBpath\&.cpp\fP\&.
.SS "bool isFile ()"

.PP
Definición en la línea \fB12\fP del archivo \fBpath\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
