.TH "Natural" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Natural
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBNatural\fP (\fBsstring\fP value)"
.br
.ti -1c
.RI "\fBNatural\fP (const char *value)"
.br
.ti -1c
.RI "\fBNatural\fP (short value)"
.br
.ti -1c
.RI "\fBNatural\fP (int value)"
.br
.ti -1c
.RI "\fBNatural\fP (long value)"
.br
.ti -1c
.RI "\fBNatural\fP (long long value)"
.br
.ti -1c
.RI "bool \fBisShort\fP ()"
.br
.ti -1c
.RI "bool \fBisInt\fP ()"
.br
.ti -1c
.RI "bool \fBisLong\fP ()"
.br
.ti -1c
.RI "bool \fBisLongLong\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB9\fP del archivo \fBnatural\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBNatural\fP (\fBsstring\fP value)\fC [inline]\fP"

.PP
Definición en la línea \fB12\fP del archivo \fBnatural\&.hpp\fP\&.
.SS "\fBNatural\fP (const char * value)"

.PP
Definición en la línea \fB18\fP del archivo \fBnatural\&.cpp\fP\&.
.SS "\fBNatural\fP (short value)"

.PP
Definición en la línea \fB14\fP del archivo \fBnatural\&.cpp\fP\&.
.SS "\fBNatural\fP (int value)"

.PP
Definición en la línea \fB15\fP del archivo \fBnatural\&.cpp\fP\&.
.SS "\fBNatural\fP (long value)"

.PP
Definición en la línea \fB16\fP del archivo \fBnatural\&.cpp\fP\&.
.SS "\fBNatural\fP (long long value)"

.PP
Definición en la línea \fB17\fP del archivo \fBnatural\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "bool isInt ()\fC [inline]\fP"

.PP
Definición en la línea \fB19\fP del archivo \fBnatural\&.hpp\fP\&.
.SS "bool isLong ()\fC [inline]\fP"

.PP
Definición en la línea \fB20\fP del archivo \fBnatural\&.hpp\fP\&.
.SS "bool isLongLong ()\fC [inline]\fP"

.PP
Definición en la línea \fB21\fP del archivo \fBnatural\&.hpp\fP\&.
.SS "bool isShort ()\fC [inline]\fP"

.PP
Definición en la línea \fB18\fP del archivo \fBnatural\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
