.TH "DateTimeImpl" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateTimeImpl
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBDateTimeImpl\fP (\fBsstring\fP str)"
.br
.ti -1c
.RI "\fBsstring\fP \fBtoString\fP ()"
.br
.ti -1c
.RI "const char * \fBtoChar\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB19\fP del archivo \fBdatetime\&.cpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBDateTimeImpl\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB21\fP del archivo \fBdatetime\&.cpp\fP\&.
.SS "\fBDateTimeImpl\fP (\fBsstring\fP str)\fC [inline]\fP"

.PP
Definición en la línea \fB23\fP del archivo \fBdatetime\&.cpp\fP\&.
.SS "~\fBDateTimeImpl\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB31\fP del archivo \fBdatetime\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "const char * toChar ()\fC [inline]\fP"

.PP
Definición en la línea \fB34\fP del archivo \fBdatetime\&.cpp\fP\&.
.SS "\fBsstring\fP toString ()\fC [inline]\fP"

.PP
Definición en la línea \fB33\fP del archivo \fBdatetime\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
