.TH "unique_impl_ptr< T, Deleter >::dummy_t_" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unique_impl_ptr< T, Deleter >::dummy_t_
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "int \fBdummy__\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<class T, class Deleter = details::default_deleter_t<T>>
.br
struct spimpl::unique_impl_ptr< T, Deleter >::dummy_t_"
.PP
Definición en la línea \fB106\fP del archivo \fBsmimplm\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "int dummy__"

.PP
Definición en la línea \fB106\fP del archivo \fBsmimplm\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
