.TH "default_deleter< T >" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
default_deleter< T >
.SH SYNOPSIS
.br
.PP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void(*)(T *)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<class T>
.br
struct spimpl::details::default_deleter< T >"
.PP
Definición en la línea \fB78\fP del archivo \fBsmimplm\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "using type =  void (*)(T*)"

.PP
Definición en la línea \fB79\fP del archivo \fBsmimplm\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
