.TH "is_default_manageable< T, D, C >" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_default_manageable< T, D, C >
.SH SYNOPSIS
.br
.PP
.PP
Herencias integral_constant< bool, std::is_same< D, default_deleter_t< T > >::value &&std::is_same< details::default_copier_t< T >, default_copier_t< T > >::value >, integral_constant< bool, std::is_same< D, default_deleter_t< T > >::value &&std::is_same< details::default_copier_t< T >, default_copier_t< T > >::value >, integral_constant< bool, std::is_same< D, default_deleter_t< T > >::value &&std::is_same< details::default_copier_t< T >, default_copier_t< T > >::value > y integral_constant< bool, std::is_same< D, default_deleter_t< T > >::value &&std::is_same< details::default_copier_t< T >, default_copier_t< T > >::value >\&.
.SH "Descripción detallada"
.PP 

.SS "template<class T, class D, class C = details::default_copier_t<T>>
.br
struct spimpl::details::is_default_manageable< T, D, C >"
.PP
Definición en la línea \fB94\fP del archivo \fBsmimplm\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
