.TH "ToolsExceptionImpl" 3 "Sábado, 20 de Noviembre de 2021" "Version 0.2.3" "Tools  for C/C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolsExceptionImpl
.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Definición en la línea \fB19\fP del archivo \fBexceptions\&.cpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBToolsExceptionImpl\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB21\fP del archivo \fBexceptions\&.cpp\fP\&.
.SS "~\fBToolsExceptionImpl\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB22\fP del archivo \fBexceptions\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Tools for C/C++ del código fuente\&.
